import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Header from '@/components/custom/header';
import StoreProvider from './StoreProvider';
import { Toaster } from '@/components/ui/sonner';
import Refresher from '@/components/custom/refresher';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${manrope.variable} antialiased min-h-screen bg-background font-marpone`}>
          <Refresher>
            <Header />
            <main>{children}</main>
            <Toaster richColors position="top-center" />
          </Refresher>
        </body>
      </StoreProvider>
    </html>
  );
}
